# Generated by Django 4.1.1 on 2022-09-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_category_products_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Изображение'),
        ),
    ]
